import {
  Account,
  BankCard,
  Beneficiary,
  SavingsGoal,
  SubscriptionItem,
  ScheduledPayment,
  BankingNotification,
  SecurityDevice,
  Transaction,
} from '../types/banking';

export const INITIAL_ACCOUNTS: Account[] = [
  {
    id: 'acc-personal',
    name: 'Personal Account',
    type: 'personal',
    balance: 12840.62,
    currency: '€',
    iban: 'PT50 0035 0123 4567 8901 2345 6',
    accountNumber: '4279',
    color: '#5C7CFF',
    monthlyDelta: 1240.0,
    isDefault: true,
  },
  {
    id: 'acc-savings',
    name: 'House Deposit Vault',
    type: 'savings',
    balance: 8410.0,
    currency: '€',
    iban: 'PT50 0035 0123 4567 8901 2345 7',
    accountNumber: '8410',
    color: '#34D399',
    monthlyDelta: 650.0,
  },
  {
    id: 'acc-travel',
    name: 'Travel & Global Vault',
    type: 'travel',
    balance: 2250.4,
    currency: '€',
    iban: 'PT50 0035 0123 4567 8901 2345 8',
    accountNumber: '2250',
    color: '#F59E0B',
    monthlyDelta: -320.0,
  },
];

export const INITIAL_CARDS: BankCard[] = [
  {
    id: 'card-black',
    accountId: 'acc-personal',
    name: 'Aura Black Titanium',
    cardholder: 'ANSHDEEP SINGH',
    numberMasked: '•••• •••• •••• 4279',
    fullNumber: '4532 8921 7340 4279',
    cvv: '839',
    expiry: '08/29',
    tier: 'black',
    isFrozen: false,
    dailyLimit: 3000,
    currentDailySpent: 1249,
    atmLimit: 1000,
    onlineLimit: 5000,
    contactlessEnabled: true,
    onlineEnabled: true,
    atmEnabled: true,
    internationalEnabled: true,
    pin: '7492',
  },
  {
    id: 'card-virtual',
    accountId: 'acc-personal',
    name: 'Aura Virtual Secure',
    cardholder: 'ANSHDEEP SINGH',
    numberMasked: '•••• •••• •••• 9014',
    fullNumber: '4532 1198 6204 9014',
    cvv: '412',
    expiry: '11/28',
    tier: 'virtual',
    isFrozen: false,
    dailyLimit: 1500,
    currentDailySpent: 28.98,
    atmLimit: 0,
    onlineLimit: 2500,
    contactlessEnabled: true,
    onlineEnabled: true,
    atmEnabled: false,
    internationalEnabled: true,
    pin: '1084',
  },
];

export const INITIAL_BENEFICIARIES: Beneficiary[] = [
  {
    id: 'ben-1',
    name: 'Emma Wilson',
    nickname: 'Emma',
    iban: 'GB49 MIDL 4005 1512 3456 78',
    bank: 'Barclays UK',
    country: 'United Kingdom',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    isFavorite: true,
  },
  {
    id: 'ben-2',
    name: 'Marco Rossi',
    nickname: 'Marco',
    iban: 'IT60 X054 2811 1010 0000 0123 456',
    bank: 'Intesa Sanpaolo',
    country: 'Italy',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    isFavorite: true,
  },
  {
    id: 'ben-3',
    name: 'Sophie Laurent',
    nickname: 'Sophie',
    iban: 'FR76 3000 4000 0112 3456 7890 143',
    bank: 'BNP Paribas',
    country: 'France',
    avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    isFavorite: true,
  },
  {
    id: 'ben-4',
    name: 'Liam van Dijk',
    nickname: 'Liam',
    iban: 'NL91 ABNA 0417 1643 00',
    bank: 'ABN AMRO',
    country: 'Netherlands',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    isFavorite: false,
  },
  {
    id: 'ben-5',
    name: 'Elena Rostova',
    nickname: 'Elena',
    iban: 'DE89 3704 0044 0532 0130 00',
    bank: 'Deutsche Bank',
    country: 'Germany',
    avatarUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
    isFavorite: false,
  },
];

export const INITIAL_SAVINGS_GOALS: SavingsGoal[] = [
  {
    id: 'goal-house',
    name: 'House Deposit',
    targetAmount: 20000,
    currentAmount: 8410,
    currency: '€',
    category: 'Real Estate',
    autoSavePercent: 15,
    color: '#5C7CFF',
  },
  {
    id: 'goal-japan',
    name: 'Kyoto Spring Trip',
    targetAmount: 3500,
    currentAmount: 2250.4,
    currency: '€',
    category: 'Travel',
    autoSavePercent: 10,
    color: '#F59E0B',
  },
];

export const INITIAL_SUBSCRIPTIONS: SubscriptionItem[] = [
  {
    id: 'sub-netflix',
    merchant: 'Netflix Premium 4K',
    category: 'Entertainment',
    amount: 17.99,
    frequency: 'Monthly',
    nextBillingDate: 'Tomorrow',
    isActive: true,
    logoInitial: 'N',
  },
  {
    id: 'sub-spotify',
    merchant: 'Spotify Duo',
    category: 'Entertainment',
    amount: 10.99,
    frequency: 'Monthly',
    nextBillingDate: '12 Sep',
    isActive: true,
    logoInitial: 'S',
  },
  {
    id: 'sub-adobe',
    merchant: 'Adobe Creative Cloud',
    category: 'Technology',
    amount: 64.99,
    frequency: 'Monthly',
    nextBillingDate: '18 Sep',
    isActive: true,
    logoInitial: 'A',
  },
  {
    id: 'sub-gym',
    merchant: 'Equinox Fitness Club',
    category: 'Health',
    amount: 39.9,
    frequency: 'Monthly',
    nextBillingDate: '4 Sep',
    isActive: true,
    logoInitial: 'E',
  },
];

export const INITIAL_SCHEDULED_PAYMENTS: ScheduledPayment[] = [
  {
    id: 'sch-1',
    title: 'Apartment Rent',
    recipientName: 'Vanguard Residential Ltd',
    recipientIban: 'PT50 0018 0000 1234 5678 9012 3',
    amount: 1150.0,
    executionDate: '1 Sep 2026',
    frequency: 'Monthly',
    accountId: 'acc-personal',
    status: 'active',
  },
  {
    id: 'sch-2',
    title: 'Equinox Gym Membership',
    recipientName: 'Equinox Fitness Europe',
    recipientIban: 'PT50 0033 0000 8877 6655 4433 2',
    amount: 39.9,
    executionDate: '4 Sep 2026',
    frequency: 'Monthly',
    accountId: 'acc-personal',
    status: 'active',
  },
  {
    id: 'sch-3',
    title: 'Netflix Premium',
    recipientName: 'Netflix International B.V.',
    recipientIban: 'NL91 ABNA 0111 2223 33',
    amount: 17.99,
    executionDate: 'Tomorrow',
    frequency: 'Monthly',
    accountId: 'acc-personal',
    status: 'active',
  },
];

export const INITIAL_NOTIFICATIONS: BankingNotification[] = [
  {
    id: 'notif-1',
    title: 'Salary Deposit Processed',
    message: 'Monthly remuneration of €3,850.00 from Aura Tech Corp has been credited to your Personal Account.',
    timestamp: '2 hours ago',
    read: false,
    type: 'transaction',
    amount: 3850,
  },
  {
    id: 'notif-2',
    title: 'Card Payment Confirmed',
    message: '€1,249.00 paid to Apple Store Covent Garden using Aura Black ••4279.',
    timestamp: '5 hours ago',
    read: false,
    type: 'transaction',
    amount: -1249,
  },
  {
    id: 'notif-3',
    title: 'Transfer Received',
    message: 'Emma Wilson sent you €250.00 with reference: Weekend getaway share.',
    timestamp: '1 day ago',
    read: true,
    type: 'transfer',
    amount: 250,
  },
  {
    id: 'notif-4',
    title: 'Upcoming Subscription Renewal',
    message: 'Netflix Premium (€17.99) is scheduled for direct debit deduction tomorrow.',
    timestamp: '1 day ago',
    read: true,
    type: 'subscription',
    amount: -17.99,
  },
  {
    id: 'notif-5',
    title: 'Security Notice: New Session',
    message: 'Authorized login detected on MacBook Air (macOS 15.1) in Lisbon, Portugal.',
    timestamp: '2 days ago',
    read: true,
    type: 'security',
  },
  {
    id: 'notif-6',
    title: 'Savings Milestone Achieved',
    message: 'Congratulations! Your House Deposit vault reached 42% (€8,410.00) of your €20,000 goal.',
    timestamp: '3 days ago',
    read: true,
    type: 'savings',
  },
];

export const INITIAL_DEVICES: SecurityDevice[] = [
  {
    id: 'dev-1',
    name: 'iPhone 16 Pro (This Device)',
    type: 'phone',
    location: 'Lisbon, Portugal',
    lastActive: 'Active now',
    isCurrent: true,
  },
  {
    id: 'dev-2',
    name: 'MacBook Air M3',
    type: 'laptop',
    location: 'Lisbon, Portugal',
    lastActive: '2 hours ago',
    isCurrent: false,
  },
  {
    id: 'dev-3',
    name: 'iPad Pro 13"',
    type: 'tablet',
    location: 'Porto, Portugal',
    lastActive: '3 days ago',
    isCurrent: false,
  },
];

const now = Date.now();
const oneHour = 3600 * 1000;
const oneDay = 24 * oneHour;

export const INITIAL_TRANSACTIONS: Transaction[] = [
  {
    id: 'tx-01',
    accountId: 'acc-personal',
    title: 'Spotify Premium',
    merchant: 'Spotify AB',
    category: 'Entertainment',
    amount: -10.99,
    type: 'outgoing',
    date: 'Today, 08:30',
    timestamp: now - oneHour * 2,
    status: 'completed',
    paymentMethod: 'Aura Virtual •• 9014',
    cardLast4: '9014',
    location: 'Stockholm, SE',
    note: 'Monthly Music Subscription',
    isRecurring: true,
    referenceId: 'AUR-TX-8921-99',
  },
  {
    id: 'tx-02',
    accountId: 'acc-personal',
    title: 'Apple Store',
    merchant: 'Apple Distribution Intl',
    category: 'Technology',
    amount: -1249.0,
    type: 'outgoing',
    date: 'Today, 06:14',
    timestamp: now - oneHour * 5,
    status: 'completed',
    paymentMethod: 'Aura Black •• 4279',
    cardLast4: '4279',
    location: 'Lisbon, PT',
    note: 'iPhone 16 Pro Titanium purchase',
    isRecurring: false,
    referenceId: 'AUR-TX-8921-98',
  },
  {
    id: 'tx-03',
    accountId: 'acc-personal',
    title: 'Monthly Salary Deposit',
    merchant: 'Aura Technologies Inc',
    category: 'Salary',
    amount: 3850.0,
    type: 'incoming',
    date: 'Yesterday',
    timestamp: now - oneDay,
    status: 'completed',
    paymentMethod: 'Direct Bank Wire',
    location: 'Amsterdam, NL',
    note: 'August Payroll Remuneration',
    isRecurring: true,
    referenceId: 'AUR-TX-8921-97',
  },
  {
    id: 'tx-04',
    accountId: 'acc-personal',
    title: 'Uber Black Ride',
    merchant: 'Uber Technologies',
    category: 'Transport',
    amount: -18.42,
    type: 'outgoing',
    date: 'Yesterday',
    timestamp: now - oneDay - oneHour * 3,
    status: 'completed',
    paymentMethod: 'Apple Pay (Aura Black)',
    cardLast4: '4279',
    location: 'Lisbon Downtown',
    note: 'Airport commute',
    isRecurring: false,
    referenceId: 'AUR-TX-8921-96',
  },
  {
    id: 'tx-05',
    accountId: 'acc-personal',
    title: 'Continente Gourmet',
    merchant: 'Continente Hipermercados',
    category: 'Groceries',
    amount: -74.28,
    type: 'outgoing',
    date: 'Yesterday',
    timestamp: now - oneDay - oneHour * 6,
    status: 'completed',
    paymentMethod: 'Aura Black •• 4279',
    cardLast4: '4279',
    location: 'Avenida da Liberdade',
    note: 'Weekly provisions & organic market',
    isRecurring: false,
    referenceId: 'AUR-TX-8921-95',
  },
  {
    id: 'tx-06',
    accountId: 'acc-personal',
    title: 'Transfer from Emma Wilson',
    merchant: 'Emma Wilson',
    category: 'Transfer',
    amount: 250.0,
    type: 'incoming',
    date: '15 Aug 2026',
    timestamp: now - oneDay * 2,
    status: 'completed',
    paymentMethod: 'SEPA Instant Transfer',
    location: 'London, UK',
    note: 'Weekend villa share settlement',
    isRecurring: false,
    referenceId: 'AUR-TX-8921-94',
  },
  {
    id: 'tx-07',
    accountId: 'acc-personal',
    title: 'Le Petit Bistro Parisien',
    merchant: 'Le Petit Bistro S.A.R.L.',
    category: 'Restaurants',
    amount: -88.5,
    type: 'outgoing',
    date: '14 Aug 2026',
    timestamp: now - oneDay * 3,
    status: 'completed',
    paymentMethod: 'Aura Black •• 4279',
    cardLast4: '4279',
    location: 'Chiado, Lisbon',
    note: 'Dinner with design partners',
    isRecurring: false,
    referenceId: 'AUR-TX-8921-93',
  },
  {
    id: 'tx-08',
    accountId: 'acc-personal',
    title: 'EDP Renewables & Power',
    merchant: 'EDP Comercial',
    category: 'Utilities',
    amount: -115.4,
    type: 'outgoing',
    date: '12 Aug 2026',
    timestamp: now - oneDay * 5,
    status: 'completed',
    paymentMethod: 'Direct Debit',
    location: 'Lisbon, PT',
    note: 'Electric & Climate utilities',
    isRecurring: true,
    referenceId: 'AUR-TX-8921-92',
  },
  {
    id: 'tx-09',
    accountId: 'acc-personal',
    title: 'Blue Bottle Specialty Coffee',
    merchant: 'Blue Bottle Roasters',
    category: 'Restaurants',
    amount: -6.8,
    type: 'outgoing',
    date: '11 Aug 2026',
    timestamp: now - oneDay * 6,
    status: 'completed',
    paymentMethod: 'Contactless Tap',
    cardLast4: '4279',
    location: 'Príncipe Real',
    note: 'Single origin pour-over',
    isRecurring: false,
    referenceId: 'AUR-TX-8921-91',
  },
  {
    id: 'tx-10',
    accountId: 'acc-personal',
    title: 'Zara Studio Flagship',
    merchant: 'Inditex Group',
    category: 'Shopping',
    amount: -142.3,
    type: 'outgoing',
    date: '9 Aug 2026',
    timestamp: now - oneDay * 8,
    status: 'completed',
    paymentMethod: 'Aura Black •• 4279',
    cardLast4: '4279',
    location: 'Rua Garrett',
    note: 'Summer collection wardrobe',
    isRecurring: false,
    referenceId: 'AUR-TX-8921-90',
  },
  {
    id: 'tx-11',
    accountId: 'acc-travel',
    title: 'Airbnb Kyoto Heritage Ryokan',
    merchant: 'Airbnb Payments UK',
    category: 'Travel',
    amount: -890.0,
    type: 'outgoing',
    date: '7 Aug 2026',
    timestamp: now - oneDay * 10,
    status: 'completed',
    paymentMethod: 'Aura Virtual •• 9014',
    cardLast4: '9014',
    location: 'Kyoto, Japan',
    note: '4-night traditional garden stay',
    isRecurring: false,
    referenceId: 'AUR-TX-8921-89',
  },
  {
    id: 'tx-12',
    accountId: 'acc-personal',
    title: 'Vanguard Loft Rent',
    merchant: 'Vanguard Residential',
    category: 'Housing',
    amount: -1450.0,
    type: 'outgoing',
    date: '1 Aug 2026',
    timestamp: now - oneDay * 16,
    status: 'completed',
    paymentMethod: 'Scheduled SEPA Transfer',
    location: 'Lisbon Central',
    note: 'August loft lease payment',
    isRecurring: true,
    referenceId: 'AUR-TX-8921-88',
  },
  {
    id: 'tx-13',
    accountId: 'acc-personal',
    title: 'Stripe Consulting Retainer',
    merchant: 'Stripe Payments Europe',
    category: 'Salary',
    amount: 1100.0,
    type: 'incoming',
    date: '28 Jul 2026',
    timestamp: now - oneDay * 20,
    status: 'completed',
    paymentMethod: 'Wire Transfer',
    location: 'Dublin, IE',
    note: 'Fintech UX advisory fee',
    isRecurring: false,
    referenceId: 'AUR-TX-8921-87',
  },
  {
    id: 'tx-14',
    accountId: 'acc-savings',
    title: 'Vault Auto-Save Allocation',
    merchant: 'Aura Smart Vaults',
    category: 'Transfer',
    amount: 500.0,
    type: 'incoming',
    date: '25 Jul 2026',
    timestamp: now - oneDay * 23,
    status: 'completed',
    paymentMethod: 'Internal Allocation',
    location: 'AURA Core',
    note: 'Monthly 15% goal auto-deposit',
    isRecurring: true,
    referenceId: 'AUR-TX-8921-86',
  },
  {
    id: 'tx-15',
    accountId: 'acc-personal',
    title: 'Lufthansa Airlines Refund',
    merchant: 'Deutsche Lufthansa AG',
    category: 'Travel',
    amount: 340.0,
    type: 'incoming',
    date: '20 Jul 2026',
    timestamp: now - oneDay * 28,
    status: 'completed',
    paymentMethod: 'Card Reimbursement',
    cardLast4: '4279',
    location: 'Frankfurt, DE',
    note: 'Flight change fare adjustment refund',
    isRecurring: false,
    referenceId: 'AUR-TX-8921-85',
  },
];
